# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Адресна допомога
description: Проект соціальної взаємодопомоги
baseurl: '' # the subpath of your site, e.g. /blog
permalink: '/blog/:title/'
url: 'http://vokov.netlify.app' # the base hostname & protocol for your site

author:
  name: з тобою
  facebook: 'tukroschu'
  twitter: 'kroschu'
  github: 'kroschu'
  linkedin: 'kroschu1'

navigation:
  - title: Головна
    url: /
  - title: Про
    url: /resume/
  - title: Радимось
    url: /contact/
  - title: Вирішуєсо
    url: /blog/
  - title: Допомагаємо
    url: /portfolio/



# Comments
allow_comments: true
comments_service: facebook
fb_app_id: 571415890410555

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      enable_comments: true
  - scope:
      path: ''
      type: portfolio
    values:
      device: desktop
      orientation: landscape
      basepath: portfolio/screenshots/

# General settings
encoding: utf-8

# Markdown settings
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules
  - assets/sass
  - assets/psd
  - docker-compose.yml
  - vendor/

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin
  - jekyll-gist

jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration
  homepage: "pages"

gist:
  noscript: false